<a href="https://colab.research.google.com/github/varshagowda1/college/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the libaries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.9.2'

Data preprocessing

Import dataset

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


Encoding categorical data

Label Encoding the ''Gender''

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2] =le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One hot encoding the 'Geography' column

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])] ,remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Feature scaling

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test= train_test_split(x,y, test_size=0.2,random_state=0) 

Building the ANN

Initializing the ANN

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
     

Adding the input layer and the first hidden layer

In [7]:

ann=tf.keras.models.Sequential()

Adding the second hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6 ,activation='relu'))

Adding the output layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6 ,activation='relu'))

Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1 ,activation='sigmoid'))

Training the ANN

Compiling the ANN

In [11]:

ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

Training the ANN on the training set

In [12]:

ann.fit(x_train,y_train,batch_size=32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5948 - accuracy: 0.7502
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4890 - accuracy: 0.8099
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4470 - accuracy: 0.8156
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4259 - accuracy: 0.8176
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4100 - accuracy: 0.8219
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3951 - accuracy: 0.8313
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3820 - accuracy: 0.8399
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3731 - accuracy: 0.8469
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3670 - accuracy: 0.8482
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3630 - accura

In [13]:

print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,5000]])>0.5))

1/1 [==============================] - 0s 97ms/step
[[0.05732922]]


Predivting thte test set results

In [14]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion matrix

In [15]:

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1595    0]
 [ 405    0]]


0.7975